import { Game, User } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    username: "MathWhiz",
    avatarUrl: "/images/avatar-placeholder.jpg",
  },
  {
    id: "u2",
    username: "ScienceGuru",
    avatarUrl: "/images/avatar-placeholder.jpg",
  },
  {
    id: "u3",
    username: "PolyglotPro",
    avatarUrl: "/images/avatar-placeholder.jpg",
  },
  {
    id: "u4",
    username: "HistoryBuff",
    avatarUrl: "/images/avatar-placeholder.jpg",
  },
];

export const MOCK_GAMES: Game[] = [
  {
    id: "g1",
    title: "Algebra Basics: Solving for X",
    description: "Master the fundamentals of linear equations in this quick 5-minute quiz.",
    topic: "Math",
    tags: ["Algebra", "Beginner", "Quiz"],
    difficulty: "Beginner",
    complexity: "Basic",
    durationMinutes: 5,
    createdBy: MOCK_USERS[0],
    createdAt: "2023-10-15T10:00:00Z",
    likesCount: 1240,
    playsCount: 5400,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-math.jpg",
    format: "Quiz",
    language: "English",
  },
  {
    id: "g2",
    title: "French Vocabulary: Animals",
    description: "Learn the names of 20 common animals in French with these interactive flashcards.",
    topic: "Languages",
    tags: ["French", "Vocabulary", "Flashcards"],
    difficulty: "Beginner",
    complexity: "Basic",
    durationMinutes: 10,
    createdBy: MOCK_USERS[2],
    createdAt: "2023-10-18T14:30:00Z",
    likesCount: 850,
    playsCount: 3200,
    isBookmarked: true,
    thumbnailUrl: "/images/game-thumb-language.jpg",
    format: "Flashcards",
    language: "French",
  },
  {
    id: "g3",
    title: "Newton's Racing Challenge",
    description: "Race against time! Solve physics problems to boost your car's speed and learn about velocity and acceleration.",
    topic: "Science",
    tags: ["Physics", "Racing", "Intermediate"],
    difficulty: "Intermediate",
    complexity: "Normal",
    durationMinutes: 15,
    createdBy: MOCK_USERS[1],
    createdAt: "2023-10-20T09:15:00Z",
    likesCount: 2100,
    playsCount: 8900,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-science.jpg",
    format: "Racing",
    language: "English",
  },
  {
    id: "g4",
    title: "World Capitals Speed Run",
    description: "How many world capitals can you name in 2 minutes?",
    topic: "Geography",
    tags: ["Geography", "Speed", "Quiz"],
    difficulty: "Intermediate",
    complexity: "Basic",
    durationMinutes: 2,
    createdBy: MOCK_USERS[2],
    createdAt: "2023-10-22T16:45:00Z",
    likesCount: 3400,
    playsCount: 12000,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-language.jpg", // Reusing for now
    format: "Quiz",
    language: "English",
  },
  {
    id: "g5",
    title: "Code Typer: Python Edition",
    description: "Type real Python code to defeat bugs and learn syntax in this fast-paced typing game.",
    topic: "Programming",
    tags: ["Python", "Coding", "Beginner"],
    difficulty: "Beginner",
    complexity: "Normal",
    durationMinutes: 20,
    createdBy: MOCK_USERS[0],
    createdAt: "2023-10-25T11:20:00Z",
    likesCount: 1800,
    playsCount: 6700,
    isBookmarked: true,
    thumbnailUrl: "/images/game-thumb-math.jpg", // Reusing for now
    format: "Simulation",
    language: "English",
  },
  {
    id: "g6",
    title: "Advanced Calculus: Derivatives",
    description: "Deep dive into differentiation rules and applications.",
    topic: "Math",
    tags: ["Calculus", "Advanced", "Quiz"],
    difficulty: "Advanced",
    complexity: "Basic",
    durationMinutes: 30,
    createdBy: MOCK_USERS[0],
    createdAt: "2023-10-28T13:10:00Z",
    likesCount: 560,
    playsCount: 1500,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-math.jpg",
    format: "Quiz",
    language: "English",
  },
  {
    id: "g7",
    title: "Spanish Conversation Starters",
    description: "Practice common greetings and introductions in Spanish.",
    topic: "Languages",
    tags: ["Spanish", "Speaking", "Scenario"],
    difficulty: "Beginner",
    complexity: "Basic",
    durationMinutes: 10,
    createdBy: MOCK_USERS[2],
    createdAt: "2023-11-01T10:00:00Z",
    likesCount: 920,
    playsCount: 4100,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-language.jpg",
    format: "Scenario",
    language: "Spanish",
  },
  {
    id: "g8",
    title: "Chronicles of Rome: The Senate",
    description: "Roleplay as a Roman Senator. Complete missions, make political alliances, and learn about the fall of the Republic.",
    topic: "History",
    tags: ["History", "RPG", "Advanced"],
    difficulty: "Advanced",
    complexity: "Complex",
    durationMinutes: 45,
    createdBy: MOCK_USERS[3],
    createdAt: "2023-11-05T15:30:00Z",
    likesCount: 1450,
    playsCount: 5600,
    isBookmarked: false,
    thumbnailUrl: "/images/game-thumb-science.jpg", // Placeholder
    format: "RPG",
    language: "English",
  },
];
